# Copyright (c) 2020, Anders Lervik.
# Distributed under the MIT License. See LICENSE for more info.
"""Version information for psynlig.

This file is generated by psynlig (``setup_version.py``).
"""
SHORT_VERSION = '0.0.6.dev0'
VERSION = '0.0.6.dev0'
FULL_VERSION = '0.0.6.dev0'
GIT_REVISION = '0b26b4524d3079494e9ab02b7b52748dad4d4785'
GIT_VERSION = '0.0.6.dev0+0b26b45'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
