# Copyright (c) 2020, Anders Lervik.
# Distributed under the MIT License. See LICENSE for more info.
"""Version information for psynlig.

This file is generated by the script ``setup_version.py``.
"""
SHORT_VERSION = '0.0.1'
VERSION = '0.0.1'
FULL_VERSION = '0.0.1'
GIT_REVISION = 'f782715210036a82bb2186e0b8c9d15721262b3e'
GIT_VERSION = '0.0.1'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
