# Copyright (c) 2020, Anders Lervik.
# Distributed under the MIT License. See LICENSE for more info.
"""Version information for psynlig.

This file is generated by the script ``setup_version.py``.
"""
SHORT_VERSION = '0.0.3'
VERSION = '0.0.3'
FULL_VERSION = '0.0.3'
GIT_REVISION = '4a955dd0c61c46fe974f1760de86c79e6ec6d28b'
GIT_VERSION = '0.0.3'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
